### ISSUE TITLE
Problems on "Basic usage"

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-instrumentation-manager#1]
Hi,

I'm following the [steps in the Basic Usage section of the documentation](https://github.com/elastest/elastest-instrumentation-manager/blob/master/docs/index.md#step-by-step) to start EIM but I'm having problems:

- In **step 1** I had to execute another different command to enter the EIM container. In the documentation it indicates the command `docker ps -a eim_eim_1 /bin/bash` but I had to use `docker exec -it container_name bash`

- In **step 2** the command `ssh -oStrictHostKeyChecking=no root@<sut_ip_address>` asked for a password for the root user but I did not know it, so I replaced the root user with elastest and I was able to connect `ssh -oStrictHostKeyChecking=no elastest@<sut_ip_address>` (with password `elastest`)

- I had no problem with **step 3**

- The real problem occurs in **step 4**, when I call the API to register the agent. The API response is as follows:

>{
       "code": 1,
       "type": "error",
       "message": "Result of the execution has been: 4 "
  }

And in `/var/log/eim` log the message that appears is the following:

>PLAY [ssh] *********************************************************************
TASK [Gathering Facts] *********************************************************
fatal: [172.23.0.11]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/var/ansible/ssh/playbook-ssh-iagent1-2017.08.30-13.52.58.retry

What am I doing wrong?

Thank you in advance for your help

**Comment by david-rojo** [comment]
Hi Edu,

Thanks for the message, because of this, I have detected some errors on the documentation that I have fixed:

- **Step 1:** you are right, the right command is the one you have used
- **Step 2:** there is no need to connect directly to the SuT, I mean to introduce the password, but is mandatory that the user used will be `root` because when you try to connect to the SuT from the EIM, the hostkey of the SuT is added to the `/root/.ssh/know_hosts` file as appears on the message: 
`Warning: Permanently added '<sut_ip>' (ECDSA) to the list of known hosts.`	If this step is not done, the execution of the step 4 fails. In order to return, please press Ctrl+C
- **Step 3:** fine as you have said
- **Step 4:** I have added extra headers to add to the API call you need to execute, but I am sure, that the error you have mentioned is because of Step 2. In this call, is needed because is the root user the one that allows the connection between SuT and EIM. We are investigating how to change this procedure to some more transparent to the user.

Tell me if everything is OK now

**Comment by EduJGURJC** [comment]
Hi, thanks for you response.

I've runned the step 2 command and i've received `ssh: connect to host 172.23.0.10 port 22: Connection refused` message, but i've re-runned the same command with a -p option and works:
>root@a175fda78f8d:/tmp# ssh -oStrictHostKeyChecking=no root@172.23.0.10 -p 22  
Warning: Permanently added '172.23.0.10' (ECDSA) to the list of known hosts.

Although when I call the api I still get the same response
>{
"code": 1,
"type": "error",
"message": "Result of the execution has been: 4 "
}

Thank you for your help

**Comment by david-rojo** [comment]
Hi,

Are you using the proposed docker image of the component for [SuT](https://hub.docker.com/r/elastest/eim-sut/) or your custom docker image? 
If your are using your custom docker image, please take in account to cover all the [prerequisites](https://github.com/elastest/elastest-instrumentation-manager/blob/master/docs/index.md#sut-prerequisites), specially the one related to the SSH server

**Comment by EduJGURJC** [comment]
Hi,

I'm using custom docker image for SuT, but is an eim-sut based image (`FROM elastest/eim-sut:0.1`).
The SuT Prerequisites are fulfilled: user 'elastest' exists and  SSH server is installed and i've tried to restart ssh service.

Thank you

**Comment by david-rojo** [comment]
Hi,

Can you use the image from SuT as it is and try to execute the Registration please? 

Specify also the changes that you have added to the image in order to try to reproduce the same environment as you have please

**Comment by EduJGURJC** [comment]
Hi,

I've tried with elastest/eim-sut:0.1 image and I still have the same problem.

Thanks

**Comment by EduJGURJC** [comment]
The problem has been solved.

On step 3, the GET call to `http://localhost:8081/eim/api/publickey` returns
>{"publickey":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkpgJYF2zUJn9uxR5EVLHdFm1h8tElM9ySL0LAmwBFNdBWSQwreNWtoiWd3CqK6xv2bzd6677hfKmcRvy2u38l0eHfMlCsvTFXxsBl/ssurTgfE5IRltEdY1gQjzFMPNmGHA2C3KiTlHrj46J82zQO3LgllLPP0TwcDhtsudO/ofQTzC/VD8tu12gIi6y1CM1VHSC6JTaBhxrQANHZ3cXxDKlZaRPhWMNfE+gKDruVtKbLjthrswMKdzG63GsrI5XIPs9EreszDswl67ZdrCyMV3vs07OBxCDNG5LakaTyXfW6DeDSv0OcNE2USMvlMmVH6QIioblbJohPWCil9EgH root@4001e309d847"}

I was copying all, but just copy the value:
>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkpgJYF2zUJn9uxR5EVLHdFm1h8tElM9ySL0LAmwBFNdBWSQwreNWtoiWd3CqK6xv2bzd6677hfKmcRvy2u38l0eHfMlCsvTFXxsBl/ssurTgfE5IRltEdY1gQjzFMPNmGHA2C3KiTlHrj46J82zQO3LgllLPP0TwcDhtsudO/ofQTzC/VD8tu12gIi6y1CM1VHSC6JTaBhxrQANHZ3cXxDKlZaRPhWMNfE+gKDruVtKbLjthrswMKdzG63GsrI5XIPs9EreszDswl67ZdrCyMV3vs07OBxCDNG5LakaTyXfW6DeDSv0OcNE2USMvlMmVH6QIioblbJohPWCil9EgH root@4001e309d847

Thank you @david-rojo

**Comment by david-rojo** [comment]
This point was not clear enough in the documentation, so I have updated it in order to explain it better. 

You are welcome @EduJGURJC
